name: "Build & Test"

on:
  pull_request:
    paths-ignore:
      - "web/**"
      - version
  push:
    paths-ignore:
      - "web/**"
      - version

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - run: nix flake check
