name: Release

on:
  push:
    paths:
      - version

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - run: nix flake check
      - run: nix build .#static
      - run: echo tag=v$(<version) >> $GITHUB_ENV
      - run: git tag ${tag}
      - run: git tag ${tag%.*}
      - run: git tag ${tag%.*.*}
      - run: git push --tags --force
      - uses: softprops/action-gh-release@v1
        with:
          files: result/bin/klunok
          tag_name: ${{env.tag}}
