name: Release

on:
  push:
    branches:
      - master
    paths:
      - version

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - run: nix flake check
      - run: nix build .#static
      - run: echo version=$(<version) >> $GITHUB_ENV
      - run: git tag ${{env.version}}
      - run: git push --tags
      - uses: softprops/action-gh-release@v1
        with:
          files: result/bin/klunok
          tag_name: ${{env.version}}
